<a href="https://colab.research.google.com/github/ShubhamBhawsar2001/Reinforcement-learning-project/blob/main/RL_Assignment1_21467.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import numpy as np
import math

class Maze:
    def __init__(self, gridHeight=6, gridWidth=6, terminalReward=10, lockPickProb=0.5):
        self.rewardsLeft = np.array([[-1, 0, 0, 0, 0, 0], 
                                    [-1, -1, 0, 0, 0,-10], 
                                    [-1, 0, 0, -1, -1, -1], 
                                    [0, 0, 0, -10, -1, -1],
                                    [-1, -1, 0, 0, -1, 0],
                                    [-1, 0, -1, 0, 0 ,-1]])

        self.rewardsRight =  np.array([[ 0, 0, 0, 0, 0, -1], 
                            [ -1, 0, 0 , 0, -10, -1],
                            [ 0, 0, -1, -1, -1, -1],
                            [ 0, 0, -10, -1, -1 ,-1],
                            [ -1, 0, 0, -1, 0, -1],
                            [ 0, -1, 0, 0, -1, -1]])

        self.rewardsUp  =  np.array([[ -1, -1, -1, -1, -1, -1], 
                            [ 0, -1, -1, -1, -1, 0],
                            [ 0, 0, -1, 0, 0, 0],
                            [ -1, 0,0, 0,0, 0],
                            [ 0, -10, -1, -1, -1, 0],
                            [ 0,  0, -1, -10, 0, 0]])


        self.rewardsDown =  np.array([[ 0, -1, -1, -1, -1, 0], 
                            [ 0, 0, -1, 0, 0, 0],
                            [ -1, 0, 0, 0, 0, 0],
                            [ 0, -10,-1,-1,-1, 0],
                            [  0,0,-1,-10,0, 0],
                            [ -1, -1, -1, 0, -1, -1]])

        self.gridHeight = gridHeight
        self.gridWidth = gridWidth
        self.lockPickProb = lockPickProb
        self.terminalReward = terminalReward


    def isStateTerminal(self, state):
        if state == (3, 0) :
            return True
        elif state == (5, 3):
            return True
        return False

    def takeAction(self, state, action):
        retVal = []
        if(self.isStateTerminal(state)):
            return [[state,1, self.terminalReward]] 

        if action=='left':
            reward = self.rewardsLeft[state]
            if(reward == -1):
                retVal.append([state,1,-1])
            elif(reward == -10):
                retVal.append([(state[0], state[1]-1),self.lockPickProb,-1])
                retVal.append([state,1-self.lockPickProb,-1])
            else:
                retVal.append([(state[0], state[1]-1),1,-1])

        if action=='right':
            reward = self.rewardsRight[state]
            if(reward == -1):
                retVal.append([state,1,-1])
            elif(reward == -10):
                retVal.append([(state[0], state[1]+1),self.lockPickProb,-1])
                retVal.append([state,1-self.lockPickProb,-1])
            else:
                retVal.append([(state[0], state[1]+1),1,-1])

        if action=='up':
            reward = self.rewardsUp[state]
            if(reward == -1):
                retVal.append([state,1,-1])
            elif(reward == -10):
                retVal.append([(state[0]-1, state[1]),self.lockPickProb,-1])
                retVal.append([state,1-self.lockPickProb,-1])
            else:
                retVal.append([(state[0]-1, state[1]),1,-1])

        if action=='down':
            reward = self.rewardsDown[state]
            if(reward == -1):
                retVal.append([state,1,-1])
            elif(reward == -10):
                retVal.append([(state[0]+1, state[1]),self.lockPickProb,-1])
                retVal.append([state,1-self.lockPickProb,-1])
            else:
                retVal.append([(state[0]+1, state[1]),1,-1])
        for i,[nextState, prob, reward] in enumerate(retVal):
            if(self.isStateTerminal(nextState)):
                retVal[i][2] = self.terminalReward   

        return retVal 
    


In [72]:
class GridworldSolution:
    def __init__(self, maze,horizonLength):
        self.env = maze
        self.actionSpace = ['left', 'right', 'up',  'down']
        self.horizonLength = horizonLength
        self.DP = np.ones((self.env.gridHeight,self.env.gridWidth,self.horizonLength),dtype = float) * -np.inf
   



    def optimalReward(self, state, k):
        optReward = -np.inf
        dp=np.matrix(np.ones((6,6)) * (-np.inf))
        dp[3,0]=20
        dp[5,3]=20
        def dpsol(self,state,k,dp,action):
          l=maze.takeAction(state,'left')
          lv=-np.inf
          r= maze.takeAction(state,'right')
          rv=-np.inf
          u= maze.takeAction(state,'up')
          uv=-np.inf
          d= maze.takeAction(state,'down')
          dv=-np.inf
          
          if  dp[state[0],state[1]]!=(-np.inf):
            return dp[state[0],state[1]]
          
          if(k>100):
            return -np.inf
          if state!=l[0][0] and (action!='right'):
           lv= l[0][2]+l[0][1]*dpsol(self,l[0][0],k+1,dp,'left')
          if state!=r[0][0] and (action!='left'):
           rv= r[0][2]+r[0][1]*dpsol(self,r[0][0],k+1,dp,'right')
          if state!=u[0][0] and (action!='down'):
           uv= u[0][2]+u[0][1]*dpsol(self,u[0][0],k+1,dp,'up')
          if state!=d[0][0] and (action!='up'):
           dv= d[0][2]+d[0][1]*dpsol(self,d[0][0],k+1,dp,'down')
          
          dp[state[0],state[1]]=max(lv,rv,uv,dv)
          return dp[state[0],state[1]]
        
        optReward=dpsol(self,state,k,dp,'any')
        #### Write your code here
        

        print(dp)
        ########
        return optReward

if __name__ == "__main__":
    maze = Maze()
    solution = GridworldSolution(maze,horizonLength=5)
    print(" Horizon ",solution.horizonLength)
    optReward = solution.optimalReward((2,0),0)
    print(optReward)
    assert optReward==28.0, 'wrong answer'

 Horizon  5
[[ 19.  20.  21.  22.  23.  24.]
 [ 18.  28.  27.  26.  25.  25.]
 [ 28.  29.  28.  23. -inf  26.]
 [ 20.  30.  29.  22. -inf  27.]
 [ 30.  27.  19.  20.  29.  28.]
 [ 29.  28. -inf  20.  30. -inf]]
28.0
